name: playground2
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flame: 1.22.0
  flame_audio: 2.1.8
  flame_behaviors: ^1.2.0
  flame_tiled: ^1.21.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

  go_router: ^14.6.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  bloc_test: ^9.1.7
  flame_test: ^1.17.1
  flutter_test:
    sdk: flutter
  mockingjay: ^0.6.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/main_character/
    - assets/tiles/
    - assets/audio/
